tutorials:
  - comment: "<!-- 1. アプリのインストール -->"
    title: "1. アプリのインストール"
    partial: "static_pages/tutorials/tutorial_1"

  - comment: "<!-- 2. 保管場所・ストックの作成 -->"
    title: "2. 保管場所・ストックの新規作成"
    partial: "static_pages/tutorials/tutorial_2"

  - comment: "<!-- 3. 保管場所・ストックの更新・削除 -->"
    title: "3. 保管場所・ストックの更新、削除"
    partial: "static_pages/tutorials/tutorial_3"

  - comment: "<!-- 4. リストの切替 -->"
    title: "4. リストの切り替え"
    partial: "static_pages/tutorials/tutorial_4"

  - comment: "<!-- 5. ストック検索機能 -->"
    title: "5. ストック検索"
    partial: "static_pages/tutorials/tutorial_5"

  - comment: "<!-- 6. ストックソート -->"
    title: "6. ストック並べ替え機能"
    partial: "static_pages/tutorials/tutorial_6"

  - comment: "<!-- 7. 保管場所へのジャンプ機能 -->"
    title: "7. 保管場所へのジャンプ"
    partial: "static_pages/tutorials/tutorial_7"

  - comment: "<!-- 8. パートナー設定機能 -->"
    title: "8. パートナー設定"
    partial: "static_pages/tutorials/tutorial_8"
